services:
  patrol:
    build: .
    image: patrol-robot:foxy
    container_name: patrol_car
    network_mode: host
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ROBOT_TYPE=x3
      - RPLIDAR_TYPE=4ROS
    volumes:
      - /home/pi/patrol_robot:/home/pi/patrol_robot
      - /dev:/dev
    working_dir: /home/pi/patrol_robot/patrol_robot
    command: bash /home/pi/patrol_robot/scripts/container_init.sh
